name: expense_tracker
description: "Expense Tracker App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.7 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.1.1
  supabase_flutter: ^2.6.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.1
  flutter_slidable: ^3.0.1
  fl_chart: ^0.66.0
  image_picker: ^1.0.7
  pdf: ^3.10.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
