/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "surface-tint": "#0c56d0",
        "on-primary": "#ffffff",
        "surface-dim": "#d9dadc",
        "on-tertiary-fixed-variant": "#743500",
        "surface-container-high": "#e7e8ea",
        "on-primary-fixed": "#001848",
        "primary": "#003d9b",
        "primary-container": "#0052cc",
        "inverse-surface": "#2e3132",
        "tertiary-fixed": "#ffdbc8",
        "surface-container": "#edeef0",
        "on-surface-variant": "#434654",
        "error": "#ba1a1a",
        "secondary-fixed": "#d5e3ff",
        "surface-variant": "#e1e2e4",
        "tertiary": "#6e3200",
        "on-surface": "#191c1e",
        "tertiary-fixed-dim": "#ffb689",
        "secondary-container": "#d0e0ff",
        "tertiary-container": "#8f470d",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#384760",
        "surface": "#f8f9fb",
        "surface-bright": "#f8f9fb",
        "on-background": "#191c1e",
        "on-primary-fixed-variant": "#0040a2",
        "on-secondary-fixed": "#0a1c33",
        "background": "#f8f9fb",
        "on-secondary-container": "#53637e",
        "on-tertiary-fixed": "#311300",
        "on-primary-container": "#c4d2ff",
        "on-error-container": "#93000a",
        "primary-fixed": "#dae2ff",
        "on-secondary": "#ffffff",
        "outline": "#737685",
        "on-tertiary-container": "#ffc7a6",
        "surface-container-highest": "#e1e2e4",
        "outline-variant": "#c3c6d6",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f4f6",
        "secondary": "#4f5f79",
        "secondary-fixed-dim": "#b7c7e5",
        "inverse-on-surface": "#f0f1f3",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#b2c5ff",
        "inverse-primary": "#b2c5ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "16px",
        xl: "32px",
        gutter: "16px",
        lg: "24px",
        "container-margin": "24px",
        xs: "4px",
        sm: "12px",
        base: "8px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-lg": ["18px", { lineHeight: "24px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
